apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: todo-ns
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80 # app port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo
    spec:
      containers:
      - env:
        - name: WORKERS_PER_CORE
          value: "0.5"
        - name: NATS_URL
          value: nats://my-nats:4222
        envFrom:
        - secretRef:
            name: postgres-env
        image: thangnv2212/todo-app
        name: todo-app
        readinessProbe:
          httpGet:
            path: /rediness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 64Mi