apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      volumes:
      - name: shared-main
        persistentVolumeClaim:
          claimName: example-claim
      containers:
        - name: pong-app
          image: thangnv2212/pong-app
          volumeMounts:
          - name: shared-main
            mountPath: /tmp
