apiVersion: v1
kind: Service
metadata:
  name: pong-svc
spec:
  type: ClusterIP
  selector:
    app: pong
  ports:
    - protocol: TCP
      port: 1234 # cluster internal port
      targetPort: 80 # app port
