apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080 # -p 8082:30080@agent[0]
      protocol: TCP
      port: 1234 # port that is available to the cluster, in this case it can be ~ anything
      targetPort: 80 # app port
