apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: todo-ns
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 1234 # cluster internal port
      targetPort: 80 # app port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-app
          image: thangnv2212/todo-app
