apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  rules:
  - http:
      paths:
      - path: /todos
        backend:
          serviceName: todo-svc
          servicePort: 1234
      - path: /static
        backend:
          serviceName: todo-svc
          servicePort: 1234
