apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: main-ns
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80 # app port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-dep
  namespace: main-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      volumes:
      - name: shared-main
        emptyDir: {}
      containers:
        - name: main-app-generator
          image: thangnv2212/main-app-generator
          volumeMounts:
          - name: shared-main
            mountPath: /tmp
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
        - name: main-app-reader
          image: thangnv2212/main-app-reader
          readinessProbe:
            httpGet:
              path: /rediness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - name: shared-main
            mountPath: /tmp
          envFrom:
          - configMapRef:
              name: dotenv-file
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
