apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: todo-cron
  namespace: todo-ns
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: write-url
            image: appropriate/curl
            command: ["/bin/sh"]
            args: ['-c', 'curl -XPOST todo-svc:1234/todos -d todo="Read $(curl -Ls -o /dev/null -w %{url_effective} https://en.wikipedia.org/wiki/Special:Random)"']
          restartPolicy: OnFailure