apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: todo-ns
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80 # app port
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-dep
  namespace: todo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: restart-rate
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-app
          image: thangnv2212/todo-app
          readinessProbe:
            httpGet:
              path: /rediness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
          - secretRef:
              name: postgres-env
          env:
          - name: WORKERS_PER_CORE
            value: "0.5"
          - name: NATS_URL
            value: nats://my-nats:4222
          resources:
            limits:
              cpu: "200m"
              memory: "64Mi"
