apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster
    spec:
      containers:
      - env:
        - name: NATS_URL
          value: nats://my-nats:4222
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - secretRef:
            name: telegram-env
        image: thangnv2212/todo-broadcaster
        name: todo-broadcaster
---