apiVersion: v1
kind: Service
metadata:
  name: pong-svc
  namespace: main-ns
spec:
  type: NodePort
  selector:
    app: pong
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80 # app port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
  namespace: main-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong-app
          image: thangnv2212/pong-app
          envFrom:
          - secretRef:
              name: postgres-env
          env:
          - name: WORKERS_PER_CORE
            value: "0.5"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pong-ingress
  namespace: main-ns
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        backend:
          serviceName: pong-svc
          servicePort: 1234
