apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: thangnv2212/todo-broadcaster
          envFrom:
          - secretRef:
              name: telegram-env
          env:
          - name: NATS_URL
            value: nats://my-nats:4222
          - name: PYTHONUNBUFFERED
            value: "1"

